name: dash
channels:
  - conda-forge
  - pytorch
dependencies:
  - python = 3.10
  - pip
  - conda-build
  - ipython
  - pandas
  - pytables
  - numpy
  - numba
  - ambertools = 23.3
  - openff-toolkit = 0.10.0
  - rdkit
  - pytorch = 2.0.0
  - pip:
    - torch_geometric == 2.3.0
