name: dash
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pip
  - ipython
  - conda-build
  - pandas
  - pytables
  - numpy
  - numba
  - ambertools = 23.3
  - openff-toolkit = 0.10.0
  - rdkit
